# Connect the API

In [1]:
#Get the API Key
from dotenv import load_dotenv
import os

#load_dotenv()

#api_token = os.getenv('API_KEY')

In [2]:
os.getcwd()

'c:\\Users\\juanm\\OneDrive\\Documentos\\@ Maestria Ie\\Term 2\\Python 2'

In [3]:
os.chdir('C:/Users/juanm/OneDrive/Documentos/@ Maestria Ie/Term 2/envPython/PythonGroupProject')
os.getcwd()

'C:\\Users\\juanm\\OneDrive\\Documentos\\@ Maestria Ie\\Term 2\\envPython\\PythonGroupProject'

In [4]:
load_dotenv()

api_token = os.getenv('API_KEY')
api_token[0:5]

'75bc1'

In [5]:
os.chdir('C:/Users/juanm/OneDrive/Documentos/@ Maestria Ie/Term 2/Python 2/SecondTerm/GroupProject')
os.getcwd()

#C:\Users\juanm\OneDrive\Documentos\@ Maestria Ie\Term 2\Python 2\SecondTerm\GroupProject

'C:\\Users\\juanm\\OneDrive\\Documentos\\@ Maestria Ie\\Term 2\\Python 2\\SecondTerm\\GroupProject'

In [6]:
#pip install simfin

In [1]:
import simfin as sf
from simfin.names import *

# Set your API-key for downloading data.
sf.set_api_key('API_KEY')

# Set the local directory where data-files are stored.
# The dir will be created if it does not already exist.
sf.set_data_dir('C:/Users/juanm/OneDrive/Documentos/@ Maestria Ie/Term 2/Python 2/SecondTerm/GroupProject')

# Download the data from the SimFin server and load into a Pandas DataFrame.
df = sf.load_shareprices(market='us')

# Print the first rows of the data.
print(df.head())

Dataset "us-shareprices-latest" not on disk.

HTTPError: 401 Client Error:  for url: https://prod.simfin.com/api/bulk-download/s3?dataset=shareprices&variant=latest&market=us

In [ ]:
import simfin as sf
from simfin.names import *
marketImport = 'us'

# Set your API-key for downloading data.
sf.set_api_key('75bc1037-74fd-4430-97f9-df067f599dd6')
sf.set_data_dir('/Workspace/Repos/Group9/ModernDataGroupProject/DownloadShareprices')

# Download the data from the SimFin server and load into a Pandas DataFrame.
df = sf.load_shareprices(market=marketImport, variant='daily')

# Display the first rows of the data.
display(df.head())

Dataset "us-shareprices-daily" on disk (0 days old).
- Loading from disk ...

c:\Users\juanm\anaconda3\Lib\site-packages\simfin\load.py:154: FutureWarning: The argument 'date_parser' is deprecated and will be removed in a future version. Please use 'date_format' instead, or read your data in as 'object' dtype and then call 'to_datetime'.
  df = pd.read_csv(path, sep=';', header=0,

Done!

                   SimFinId   Open   High    Low  Close  Adj. Close   Volume  \
Ticker Date
A      2019-04-11     45846  81.88  81.92  80.89  81.08       77.87  1071479
       2019-04-12     45846  81.43  82.06  80.90  80.98       77.77  1249295
       2019-04-15     45846  81.00  81.13  79.91  80.40       77.22  1627268
       2019-04-16     45846  80.82  80.96  77.19  77.55       74.48  3441597
       2019-04-17     45846  78.15  78.32  74.46  75.43       72.44  4471971
...                     ...    ...    ...    ...    ...         ...      ...
ZYXI   2024-03-01    171401  12.05  13.43  12.00  12.30       12.30  1216112
       2024-03-04    171401  12.26  12.98  12.26  12.57       12.57   349550
       2024-03-05    171401  12.61  12.96  12.52  12.87       12.87   186852
       2024-03-06    171401  13.03  13.03  12.45  12.73       12.73   147222
       2024-03-07    171401  12.69  12.92  12.66  12.68       12.68   113824

                   Dividend  Shares Outstanding
Ticker Date
A      2019-04-11       NaN         317515869.0
       2019-04-12       NaN         317515869.0
       2019-04-15       NaN         317515869.0
       2019-04-16       NaN         317515869.0
       2019-04-17       NaN         317515869.0
...                     ...                 ...
ZYXI   2024-03-01       NaN          32170182.0
       2024-03-04       NaN          32170182.0
       2024-03-05       NaN          32170182.0
       2024-03-06       NaN          32170182.0
       2024-03-07       NaN          32170182.0

[5815259 rows x 9 columns]

In [15]:
display(df.tail())

                   SimFinId   Open   High    Low  Close  Adj. Close  Volume  \
Ticker Date
ZYXI   2024-03-08    171401  12.78  13.19  12.74  12.86       12.86  213848
       2024-03-11    171401  12.83  13.07  12.67  12.69       12.69  150265
       2024-03-12    171401  12.69  12.87  12.59  12.60       12.60  151053
       2024-03-13    171401  12.57  12.81  12.57  12.69       12.69   89921
       2024-03-14    171401  12.69  12.73  12.18  12.19       12.19  313909

                   Dividend  Shares Outstanding
Ticker Date
ZYXI   2024-03-08       NaN          32170182.0
       2024-03-11       NaN          32170182.0
       2024-03-12       NaN          32170182.0
       2024-03-13       NaN          32170182.0
       2024-03-14       NaN          32170182.0

In [13]:
Bdf.loc['B':'B']

NameError: name 'Bdf' is not defined

In [ ]:
import simfin as sf
from simfin.names import *
marketImport = 'us'

# Set your API-key for downloading data.
sf.set_api_key('75bc1037-74fd-4430-97f9-df067f599dd6')
sf.set_data_dir('/Workspace/Repos/Group9/ModernDataGroupProject/DownloadShareprices')

# Download the data from the SimFin server and load into a Pandas DataFrame.
df = sf.load_shareprices(market=marketImport)

# Display the first rows of the data.
display(df.head())